_base_: ./base_config.yaml

model_params:
  mode: 'moe_lora'
  base_model_name: 'deit_small_patch16_224'
  num_experts: 4
  lora_rank: 7
  lora_alpha: 14
  k: 2
  target_blocks_indices: [8, 9, 10, 11]

train_params:
  learning_rate: 0.0001
  aux_loss_weight: 0.01